# Generated by Django 5.1.1 on 2024-10-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Betslip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('correct_score', 'Correct Score'), ('yesterday', 'Yesterday')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='odds',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
